// AUTO-GENERATED by scripts/build-icons.mjs from ./svg/*.svg.
// Do not edit by hand — edit the SVG source and run `npm run build:icons`.
import type { SVGProps } from "react";

export interface IconProps extends SVGProps<SVGSVGElement> {
  /** Square size in pixels; overridden by explicit width/height. */
  size?: number | string;
  /** Accessible title rendered as an SVG <title> element. */
  title?: string;
}

export const IconArrowLeftFill18 = ({ size = 18, width, height, title, ...props }: IconProps) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    viewBox="0 0 18 18"
    width={width ?? size}
    height={height ?? size}
    {...props}
  >
    {title ? <title>{title}</title> : null}
      <path d="M15.25,9.75H3c-.414,0-.75-.336-.75-.75s.336-.75,.75-.75H15.25c.414,0,.75,.336,.75,.75s-.336,.75-.75,.75Z" fill="currentColor" data-color="color-2" />
      <path d="M7,14c-.192,0-.384-.073-.53-.22L2.22,9.53c-.293-.293-.293-.768,0-1.061L6.47,4.22c.293-.293,.768-.293,1.061,0s.293,.768,0,1.061l-3.72,3.72,3.72,3.72c.293,.293,.293,.768,0,1.061-.146,.146-.338,.22-.53,.22Z" fill="currentColor" />
  </svg>
);

export const IconArrowRightFill18 = ({ size = 18, width, height, title, ...props }: IconProps) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    viewBox="0 0 18 18"
    width={width ?? size}
    height={height ?? size}
    {...props}
  >
    {title ? <title>{title}</title> : null}
      <path d="M15,9.75H2.75c-.414,0-.75-.336-.75-.75s.336-.75,.75-.75H15c.414,0,.75,.336,.75,.75s-.336,.75-.75,.75Z" fill="currentColor" data-color="color-2" />
      <path d="M11,14c-.192,0-.384-.073-.53-.22-.293-.293-.293-.768,0-1.061l3.72-3.72-3.72-3.72c-.293-.293-.293-.768,0-1.061s.768-.293,1.061,0l4.25,4.25c.293,.293,.293,.768,0,1.061l-4.25,4.25c-.146,.146-.338,.22-.53,.22Z" fill="currentColor" />
  </svg>
);

export const IconBathtubFillDuo18 = ({ size = 18, width, height, title, ...props }: IconProps) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    viewBox="0 0 18 18"
    width={width ?? size}
    height={height ?? size}
    {...props}
  >
    {title ? <title>{title}</title> : null}
      <path d="M3.5 4C3.5 2.34279 4.84279 1 6.5 1C8.15721 1 9.5 2.34279 9.5 4C9.5 4.41421 9.16421 4.75 8.75 4.75C8.33579 4.75 8 4.41421 8 4C8 3.17121 7.32879 2.5 6.5 2.5C5.67121 2.5 5 3.17121 5 4V8.75C5 9.16421 4.66421 9.5 4.25 9.5C3.83579 9.5 3.5 9.16421 3.5 8.75V4Z" fillRule="evenodd" clipRule="evenodd" fill="currentColor" />
      <path d="M2 8.75C2 8.33579 2.33579 8 2.75 8H15.25C15.6642 8 16 8.33579 16 8.75V11.25C16 13.3212 14.3212 15 12.25 15H5.75C3.67879 15 2 13.3212 2 11.25V8.75Z" fillRule="evenodd" clipRule="evenodd" fill="currentColor" fillOpacity="0.4" data-color="color-2" />
      <path d="M1 8.75C1 8.33579 1.33579 8 1.75 8H16.25C16.6642 8 17 8.33579 17 8.75C17 9.16421 16.6642 9.5 16.25 9.5H1.75C1.33579 9.5 1 9.16421 1 8.75Z" fillRule="evenodd" clipRule="evenodd" fill="currentColor" />
      <path d="M11.5 15V16.25C11.5 16.6642 11.8358 17 12.25 17C12.6642 17 13 16.6642 13 16.25V14.925C12.7577 14.9742 12.5069 15 12.25 15H11.5Z" fill="currentColor" />
      <path d="M5 14.925V16.25C5 16.6642 5.33579 17 5.75 17C6.16421 17 6.5 16.6642 6.5 16.25V15H5.75C5.49315 15 5.24233 14.9742 5 14.925Z" fill="currentColor" />
  </svg>
);

export const IconBedDoubleFillDuo18 = ({ size = 18, width, height, title, ...props }: IconProps) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    viewBox="0 0 18 18"
    width={width ?? size}
    height={height ?? size}
    {...props}
  >
    {title ? <title>{title}</title> : null}
      <path d="M2 3.75C2 2.78379 2.78379 2 3.75 2H14.25C15.2162 2 16 2.78379 16 3.75V10.75C16 11.1642 15.6642 11.5 15.25 11.5H2.75C2.33579 11.5 2 11.1642 2 10.75V3.75Z" fillRule="evenodd" clipRule="evenodd" fill="currentColor" fillOpacity="0.4" data-color="color-2" />
      <path d="M17 11.75C17 10.2308 15.7692 9 14.25 9H3.75C2.23079 9 1 10.2308 1 11.75V15.25C1 15.6642 1.33579 16 1.75 16C2.16421 16 2.5 15.6642 2.5 15.25V14H15.5V15.25C15.5 15.6642 15.8358 16 16.25 16C16.6642 16 17 15.6642 17 15.25V11.75Z" fillRule="evenodd" clipRule="evenodd" fill="currentColor" />
      <path d="M8.25 5.25C8.25 4.83579 7.91421 4.5 7.5 4.5H5.75C5.336 4.5 5 4.836 5 5.25V6.75C5 7.16421 5.33579 7.5 5.75 7.5H7.5C7.91421 7.5 8.25 7.16421 8.25 6.75V5.25Z" fill="currentColor" />
      <path d="M12.25 4.5H10.5C10.0858 4.5 9.75 4.83579 9.75 5.25V6.75C9.75 7.16421 10.0858 7.5 10.5 7.5H12.25C12.6642 7.5 13 7.16421 13 6.75V5.25C13 4.836 12.664 4.5 12.25 4.5Z" fill="currentColor" />
  </svg>
);

export const IconCalendarFillDuo18 = ({ size = 18, width, height, title, ...props }: IconProps) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    viewBox="0 0 18 18"
    width={width ?? size}
    height={height ?? size}
    {...props}
  >
    {title ? <title>{title}</title> : null}
      <path d="m1.5,5.5v8.25c0,1.5186,1.2307,2.75,2.75,2.75h9.5c1.5193,0,2.75-1.2314,2.75-2.75V5.5H1.5Z" fill="currentColor" fillRule="evenodd" opacity=".4" strokeWidth="0" data-color="color-2" />
      <path d="m6.5,1.25c0-.4142-.3358-.75-.75-.75s-.75.3358-.75.75v1.25h-.75c-1.5192,0-2.75,1.2308-2.75,2.75v1.25h15v-1.25c0-1.5192-1.2308-2.75-2.75-2.75h-.75v-1.25c0-.4142-.3358-.75-.75-.75s-.75.3358-.75.75v1.25h-5v-1.25Z" fillRule="evenodd" strokeWidth="0" fill="currentColor" />
  </svg>
);

export const IconChevronDownFill18 = ({ size = 18, width, height, title, ...props }: IconProps) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    viewBox="0 0 18 18"
    width={width ?? size}
    height={height ?? size}
    {...props}
  >
    {title ? <title>{title}</title> : null}
      <path d="M9,13.5c-.192,0-.384-.073-.53-.22L2.22,7.03c-.293-.293-.293-.768,0-1.061s.768-.293,1.061,0l5.72,5.72,5.72-5.72c.293-.293,.768-.293,1.061,0s.293,.768,0,1.061l-6.25,6.25c-.146,.146-.338,.22-.53,.22Z" fill="currentColor" />
  </svg>
);

export const IconChevronLeftFill18 = ({ size = 18, width, height, title, ...props }: IconProps) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    viewBox="0 0 18 18"
    width={width ?? size}
    height={height ?? size}
    {...props}
  >
    {title ? <title>{title}</title> : null}
      <path d="M11.5,16c-.192,0-.384-.073-.53-.22l-6.25-6.25c-.293-.293-.293-.768,0-1.061L10.97,2.22c.293-.293,.768-.293,1.061,0s.293,.768,0,1.061l-5.72,5.72,5.72,5.72c.293,.293,.293,.768,0,1.061-.146,.146-.338,.22-.53,.22Z" fill="currentColor" />
  </svg>
);

export const IconConciergeFill24 = ({ size = 24, width, height, title, ...props }: IconProps) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    viewBox="0 0 24 24"
    width={width ?? size}
    height={height ?? size}
    {...props}
  >
    {title ? <title>{title}</title> : null}
      <path d="M8.02344 1.62114C10.6093 0.790349 13.3907 0.790352 15.9766 1.62114L18 2.27055L17.8008 7.46484C13.4745 6.59958 10.4354 6.61626 6.16899 7.46954L6 2.27055L8.02344 1.62114Z" fill="currentColor" data-color="color-2" />
      <path d="M6.50671 9.43849C10.4239 8.66664 13.5212 8.65628 17.4921 9.43849L17.1874 11.2285C16.9446 12.6536 16.117 13.8602 14.9696 14.6289V16.2422C14.9696 16.338 14.9758 16.4272 14.9852 16.5108L11.9989 18.75L9.01355 16.5098C9.02289 16.4265 9.03014 16.3377 9.03015 16.2422V14.6289C7.88282 13.8602 7.05514 12.6535 6.81238 11.2285L6.50671 9.43849Z" fill="currentColor" />
      <path d="M11 20.499V23H1V21.9609C1.00007 20.6224 1.88708 19.4459 3.17383 19.0771C4.60451 18.6673 6.03367 18.2518 7.4668 17.8506L11 20.499ZM7 20C6.44772 20 6 20.4477 6 21C6 21.5523 6.44772 22 7 22C7.55228 22 8 21.5523 8 21C8 20.4477 7.55228 20 7 20Z" fillRule="evenodd" clipRule="evenodd" fill="currentColor" />
      <path d="M20.8262 19.0771C22.1129 19.4459 22.9999 20.6224 23 21.9609V23H13V20.499L16.5312 17.8496C17.965 18.2512 19.3948 18.6671 20.8262 19.0771ZM17 20C16.4477 20 16 20.4477 16 21C16 21.5523 16.4477 22 17 22C17.5523 22 18 21.5523 18 21C18 20.4477 17.5523 20 17 20Z" fillRule="evenodd" clipRule="evenodd" fill="currentColor" />
  </svg>
);

export const IconCurrencyDollarFillDuo18 = ({ size = 18, width, height, title, ...props }: IconProps) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    viewBox="0 0 18 18"
    width={width ?? size}
    height={height ?? size}
    {...props}
  >
    {title ? <title>{title}</title> : null}
      <path d="M9 1C9.41421 1 9.75 1.33579 9.75 1.75V3C9.75 3.41421 9.41421 3.75 9 3.75C8.58579 3.75 8.25 3.41421 8.25 3V1.75C8.25 1.33579 8.58579 1 9 1Z" fillRule="evenodd" clipRule="evenodd" fill="currentColor" fillOpacity="0.4" data-color="color-2" />
      <path d="M9 14.25C9.41421 14.25 9.75 14.5858 9.75 15V16.25C9.75 16.6642 9.41421 17 9 17C8.58579 17 8.25 16.6642 8.25 16.25V15C8.25 14.5858 8.58579 14.25 9 14.25Z" fillRule="evenodd" clipRule="evenodd" fill="currentColor" fillOpacity="0.4" data-color="color-2" />
      <path d="M4 6.3748C4 4.51089 5.51098 2.99989 7.3749 2.99989H13C13.4142 2.99989 13.75 3.33568 13.75 3.74989C13.75 4.16411 13.4142 4.49989 13 4.49989H7.3749C6.33942 4.49989 5.5 5.33931 5.5 6.3748C5.5 7.41052 6.33964 8.25031 7.3749 8.25031H10.6252C12.4891 8.25031 14.0001 9.76129 14.0001 11.6252C14.0001 13.4891 12.4891 15.0001 10.6252 15.0001H5.0001C4.58589 15.0001 4.2501 14.6643 4.2501 14.2501C4.2501 13.8359 4.58589 13.5001 5.0001 13.5001H10.6252C11.6607 13.5001 12.5001 12.6607 12.5001 11.6252C12.5001 10.5897 11.6607 9.75031 10.6252 9.75031H7.3749C5.51076 9.75031 4 8.23849 4 6.3748Z" fillRule="evenodd" clipRule="evenodd" fill="currentColor" />
  </svg>
);

export const IconDishwasherFill24 = ({ size = 24, width, height, title, ...props }: IconProps) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    viewBox="0 0 24 24"
    width={width ?? size}
    height={height ?? size}
    {...props}
  >
    {title ? <title>{title}</title> : null}
      <path d="M22 19C22 20.6569 20.6569 22 19 22H5C3.34315 22 2 20.6569 2 19V8H22V19ZM6.13281 17.6221L8.06543 18.1396L9.87695 11.3779L7.94531 10.8604L6.13281 17.6221ZM10.1328 17.6221L12.0654 18.1396L13.877 11.3779L11.9453 10.8604L10.1328 17.6221ZM14.1328 17.6221L16.0654 18.1396L17.877 11.3779L15.9453 10.8604L14.1328 17.6221Z" fillRule="evenodd" clipRule="evenodd" fill="currentColor" />
      <path d="M19 2C20.6569 2 22 3.34315 22 5V6H15V5H9V6H2V5C2 3.34315 3.34315 2 5 2H19Z" fill="currentColor" data-color="color-2" />
  </svg>
);

export const IconDumbbellFill24 = ({ size = 24, width, height, title, ...props }: IconProps) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    viewBox="0 0 24 24"
    width={width ?? size}
    height={height ?? size}
    {...props}
  >
    {title ? <title>{title}</title> : null}
      <path d="M17 11V13H6V11H17Z" fill="currentColor" data-color="color-2" />
      <path d="M5 11V13H0V11H5Z" fill="currentColor" data-color="color-2" />
      <path d="M24 11V13H19V11H24Z" fill="currentColor" data-color="color-2" />
      <path d="M16 4.5C16 3.11929 17.1193 2 18.5 2C19.8807 2 21 3.11929 21 4.5V19.5C21 20.8807 19.8807 22 18.5 22C17.1193 22 16 20.8807 16 19.5V4.5Z" fill="currentColor" />
      <path d="M3 4.5C3 3.11929 4.11929 2 5.5 2C6.88071 2 8 3.11929 8 4.5V19.5C8 20.8807 6.88071 22 5.5 22C4.11929 22 3 20.8807 3 19.5V4.5Z" fill="currentColor" />
  </svg>
);

export const IconFilterFill18 = ({ size = 18, width, height, title, ...props }: IconProps) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    viewBox="0 0 18 18"
    width={width ?? size}
    height={height ?? size}
    {...props}
  >
    {title ? <title>{title}</title> : null}
      <path d="M15.25,2H2.75c-.285,0-.545,.161-.671,.416-.127,.255-.098,.56,.074,.787l4.848,6.399v6.648c0,.265,.14,.511,.368,.646,.118,.07,.25,.104,.382,.104,.125,0,.249-.031,.361-.093l2.5-1.375c.24-.132,.389-.384,.389-.657v-5.273L15.848,3.203c.172-.227,.201-.532,.074-.787-.126-.255-.387-.416-.671-.416Z" fill="currentColor" />
  </svg>
);

export const IconFilterFillDuo18 = ({ size = 18, width, height, title, ...props }: IconProps) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    viewBox="0 0 18 18"
    width={width ?? size}
    height={height ?? size}
    {...props}
  >
    {title ? <title>{title}</title> : null}
      <path d="M2.74999 2C2.46499 2 2.20499 2.161 2.07899 2.416C1.95199 2.671 1.98099 2.976 2.15299 3.203L7.00099 9.602V16.25C7.00099 16.515 7.14099 16.761 7.36899 16.896C7.48699 16.966 7.61899 17 7.75099 17C7.87599 17 7.99999 16.969 8.11199 16.907L10.612 15.532C10.852 15.4 11.001 15.148 11.001 14.875V9.602L15.848 3.203C16.02 2.976 16.049 2.671 15.922 2.416C15.796 2.161 15.535 2 15.251 2H2.74999Z" fill="currentColor" fillOpacity="0.4" data-color="color-2" />
  </svg>
);

export const IconHeartFill18 = ({ size = 18, width, height, title, ...props }: IconProps) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    viewBox="0 0 18 18"
    width={width ?? size}
    height={height ?? size}
    {...props}
  >
    {title ? <title>{title}</title> : null}
      <path d="M12.164,2c-1.195,.015-2.324,.49-3.164,1.306-.84-.815-1.972-1.291-3.178-1.306-2.53,.015-4.582,2.084-4.572,4.609,0,5.253,5.306,8.429,6.932,9.278,.256,.133,.537,.2,.818,.2s.562-.067,.817-.2c1.626-.848,6.933-4.024,6.933-9.275,.009-2.528-2.042-4.597-4.586-4.612Z" fill="currentColor" />
  </svg>
);

export const IconHeartFillDuo18 = ({ size = 18, width, height, title, ...props }: IconProps) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    viewBox="0 0 18 18"
    width={width ?? size}
    height={height ?? size}
    {...props}
  >
    {title ? <title>{title}</title> : null}
      <path d="M8.999 16.0874C8.7187 16.0874 8.43849 16.0205 8.18259 15.8872C6.55659 15.0381 1.25101 11.8603 1.25101 6.6089C1.24121 4.0845 3.292 2.0156 5.8223 2C7.0284 2.0151 8.1592 2.4902 9 3.3057C9.8398 2.4903 10.9678 2.0152 12.1631 2C14.708 2.0156 16.7588 4.0845 16.749 6.6118C16.749 11.8618 11.4433 15.0386 9.81641 15.8872C9.56051 16.0205 9.2803 16.0874 8.999 16.0874Z" fill="currentColor" fillOpacity="0.4" data-color="color-2" />
  </svg>
);

export const IconHouseSearchFill24 = ({ size = 24, width, height, title, ...props }: IconProps) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    viewBox="0 0 24 24"
    width={width ?? size}
    height={height ?? size}
    {...props}
  >
    {title ? <title>{title}</title> : null}
      <path d="M11.5 12.9999C10.1193 12.9999 9 14.1192 9 15.4999C9 16.8806 10.1193 17.9999 11.5 17.9999C12.8807 17.9999 14 16.8806 14 15.4999C14 14.1192 12.8807 12.9999 11.5 12.9999Z" fill="currentColor" />
      <path d="M3 13.2395V19.9999C3 21.6567 4.34315 22.9999 6 22.9999H18C19.6569 22.9999 21 21.6567 21 19.9999V13.2395L12 5.87598L3 13.2395ZM7 15.4999C7 13.0146 9.01472 10.9999 11.5 10.9999C13.9853 10.9999 16 13.0146 16 15.4999C16 16.3804 15.7471 17.2019 15.31 17.8956L17.4142 19.9999L16 21.4141L13.8957 19.3098C13.202 19.747 12.3805 19.9999 11.5 19.9999C9.01472 19.9999 7 17.9852 7 15.4999Z" fillRule="evenodd" clipRule="evenodd" fill="currentColor" />
      <path d="M11.9999 0.713379L23.9064 10.3519L22.648 11.9064L11.9999 3.28657L1.3519 11.9064L0.0935059 10.3519L11.9999 0.713379Z" fillRule="evenodd" clipRule="evenodd" fill="currentColor" data-color="color-2" />
  </svg>
);

export const IconMinusFill18 = ({ size = 18, width, height, title, ...props }: IconProps) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    viewBox="0 0 18 18"
    width={width ?? size}
    height={height ?? size}
    {...props}
  >
    {title ? <title>{title}</title> : null}
      <path d="M14.75,9.75H3.25c-.414,0-.75-.336-.75-.75s.336-.75,.75-.75H14.75c.414,0,.75,.336,.75,.75s-.336,.75-.75,.75Z" fill="currentColor" />
  </svg>
);

export const IconPawFill24 = ({ size = 24, width, height, title, ...props }: IconProps) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    viewBox="0 0 24 24"
    width={width ?? size}
    height={height ?? size}
    {...props}
  >
    {title ? <title>{title}</title> : null}
      <path d="M9.11917 10.9202C10.0112 10.375 11.005 10 12 10C12.995 10 13.9888 10.375 14.8808 10.9202C15.7816 11.4706 16.6406 12.2316 17.3843 13.0992C18.8487 14.8078 20 17.0932 20 19.25C20 20.274 19.5554 21.2365 18.797 21.9317C18.0416 22.6242 17.0341 23 16 23C14.7922 23 14.1396 22.7057 13.5833 22.4507L13.5663 22.4429C13.1306 22.2432 12.782 22.0833 12 22.0833C11.218 22.0833 10.8694 22.2432 10.4337 22.4429L10.4167 22.4507C9.86038 22.7057 9.20782 23 8 23C6.96586 23 5.95844 22.6242 5.20296 21.9317C4.44456 21.2365 4 20.274 4 19.25C4 17.0932 5.15125 14.8078 6.61574 13.0992C7.35943 12.2316 8.21844 11.4706 9.11917 10.9202Z" fillRule="evenodd" clipRule="evenodd" fill="currentColor" data-color="color-2" />
      <path d="M18.5 11C18.5 9.53152 19.4554 8 21 8C22.5446 8 23.5 9.53152 23.5 11C23.5 12.4685 22.5446 14 21 14C19.4554 14 18.5 12.4685 18.5 11Z" fillRule="evenodd" clipRule="evenodd" fill="currentColor" />
      <path d="M0.5 11C0.5 9.53152 1.45537 8 3 8C4.54463 8 5.5 9.53152 5.5 11C5.5 12.4685 4.54463 14 3 14C1.45537 14 0.5 12.4685 0.5 11Z" fillRule="evenodd" clipRule="evenodd" fill="currentColor" />
      <path d="M13 5C13 3.22316 14.2035 1.5 16 1.5C17.7965 1.5 19 3.22316 19 5C19 6.77684 17.7965 8.5 16 8.5C14.2035 8.5 13 6.77684 13 5Z" fillRule="evenodd" clipRule="evenodd" fill="currentColor" />
      <path d="M5 5C5 3.22316 6.20346 1.5 8 1.5C9.79654 1.5 11 3.22316 11 5C11 6.77684 9.79654 8.5 8 8.5C6.20346 8.5 5 6.77684 5 5Z" fillRule="evenodd" clipRule="evenodd" fill="currentColor" />
  </svg>
);

export const IconPlusFill18 = ({ size = 18, width, height, title, ...props }: IconProps) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    viewBox="0 0 18 18"
    width={width ?? size}
    height={height ?? size}
    {...props}
  >
    {title ? <title>{title}</title> : null}
      <path d="M14.75,9.75H3.25c-.414,0-.75-.336-.75-.75s.336-.75,.75-.75H14.75c.414,0,.75,.336,.75,.75s-.336,.75-.75,.75Z" fill="currentColor" data-color="color-2" />
      <path d="M9,15.5c-.414,0-.75-.336-.75-.75V3.25c0-.414,.336-.75,.75-.75s.75,.336,.75,.75V14.75c0,.414-.336,.75-.75,.75Z" fill="currentColor" />
  </svg>
);

export const IconUserArrowRightFillDuo18 = ({ size = 18, width, height, title, ...props }: IconProps) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    viewBox="0 0 18 18"
    width={width ?? size}
    height={height ?? size}
    {...props}
  >
    {title ? <title>{title}</title> : null}
      <path d="M14.7803 9.71967C14.4874 9.42678 14.0126 9.42678 13.7197 9.71967C13.4268 10.0126 13.4268 10.4874 13.7197 10.7803L14.9393 12H11.75C11.3358 12 11 12.3358 11 12.75C11 13.1642 11.3358 13.5 11.75 13.5H14.9393L13.7197 14.7197C13.4268 15.0126 13.4268 15.4874 13.7197 15.7803C14.0126 16.0732 14.4874 16.0732 14.7803 15.7803L17.2803 13.2803C17.5732 12.9874 17.5732 12.5126 17.2803 12.2197L14.7803 9.71967Z" fillRule="evenodd" clipRule="evenodd" fill="currentColor" />
      <path d="M12.4735 16.6313C12.1038 16.157 11.9506 15.5688 12.0138 15H11.7499C10.5073 15 9.49993 13.9927 9.49993 12.75C9.49993 11.5074 10.5073 10.5 11.7499 10.5H12.0138C11.9844 10.2355 12.0018 9.96679 12.066 9.70729C11.1409 9.25441 10.1006 9 8.99993 9C6.14161 9 3.69052 10.7157 2.60511 13.1674C2.05155 14.4186 2.74419 15.8317 4.01253 16.2313C5.29497 16.6354 6.99277 17 8.99993 17C10.2964 17 11.4638 16.8479 12.4735 16.6313Z" fill="currentColor" fillOpacity="0.4" data-color="color-2" />
      <path d="M9 7.50049C10.7952 7.50049 12.25 6.04543 12.25 4.25049C12.25 2.45554 10.7952 1.00049 9 1.00049C7.20482 1.00049 5.75 2.45554 5.75 4.25049C5.75 6.04543 7.20482 7.50049 9 7.50049Z" fill="currentColor" fillOpacity="0.4" data-color="color-2" />
  </svg>
);

export const IconWashingMachineFill24 = ({ size = 24, width, height, title, ...props }: IconProps) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    viewBox="0 0 24 24"
    width={width ?? size}
    height={height ?? size}
    {...props}
  >
    {title ? <title>{title}</title> : null}
      <path d="M8 14C8 11.7909 9.79086 10 12 10H13V12H12C10.8954 12 10 12.8954 10 14V15H8V14Z" fillRule="evenodd" clipRule="evenodd" fill="currentColor" data-color="color-2" />
      <path d="M6 23H18C19.6568 23 21 21.6569 21 20L21 4C21 2.34315 19.6568 1 18 1H6C4.34315 1 3 2.34315 3 4V20C3 21.6569 4.34314 23 6 23ZM12 8C8.68628 8 5.99999 10.6863 5.99999 14C5.99999 17.3137 8.68628 20 12 20C15.3137 20 18 17.3137 18 14C18 10.6863 15.3137 8 12 8ZM9.99999 6H5.99999V4H9.99999V6ZM18 5.99999L18 3.99999L15.99 4.00001L15.99 6.00001L18 5.99999Z" fillRule="evenodd" clipRule="evenodd" fill="currentColor" />
  </svg>
);

export const IconWifiFill24 = ({ size = 24, width, height, title, ...props }: IconProps) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    viewBox="0 0 24 24"
    width={width ?? size}
    height={height ?? size}
    {...props}
  >
    {title ? <title>{title}</title> : null}
      <path d="M4.22182 12.2218C6.21133 10.2323 8.9627 9 12 9C15.0373 9 17.7887 10.2323 19.7782 12.2218L20.4853 12.9289L19.0711 14.3431L18.364 13.636C16.7342 12.0063 14.4855 11 12 11C9.51443 11 7.2658 12.0063 5.63603 13.636L4.92892 14.3431L3.51471 12.9289L4.22182 12.2218Z" fillRule="evenodd" clipRule="evenodd" fill="currentColor" data-color="color-2" />
      <path d="M7.76079 15.7539C8.84522 14.6713 10.3452 14 12 14C13.6548 14 15.1548 14.6713 16.2392 15.7539L16.9498 16.464L12 21.4085L7.05255 16.461L7.76079 15.7539Z" fillRule="evenodd" clipRule="evenodd" fill="currentColor" />
      <path d="M0.719673 8.653C3.61135 5.77822 7.59898 4 12 4C16.4095 4 20.404 5.78508 23.297 8.66965L24.0052 9.37572L22.593 10.792L21.8849 10.0859C19.3515 7.55991 15.8589 6 12 6C8.14855 6 4.66197 7.55391 2.12974 10.0714L1.42056 10.7764L0.010498 9.35803L0.719673 8.653Z" fillRule="evenodd" clipRule="evenodd" fill="currentColor" />
  </svg>
);
