// Generate app/_components/ui/icons/index.tsx from the SVG files in
// app/_components/ui/icons/svg/*.svg.
//
// The SVGs are the source of truth. To add/replace an icon, drop a `<svg>` file
// into the svg/ folder (kebab-case name, e.g. `arrow-up-fill-18.svg`) and run:
//     npm run build:icons
//
// Each SVG becomes a typed React component named from its file
// (`arrow-up-fill-18.svg` -> `IconArrowUpFill18`). Icons render inline so they
// inherit `currentColor` from surrounding text.
import { readdir, readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";

const ICONS_DIR = resolve(process.cwd(), "app/_components/ui/icons");
const SVG_DIR = resolve(ICONS_DIR, "svg");
const OUT_FILE = resolve(ICONS_DIR, "index.tsx");

// SVG (kebab) attribute -> JSX (camel) attribute. data-*/aria-* pass through.
const ATTR_MAP = {
  "fill-rule": "fillRule",
  "clip-rule": "clipRule",
  "fill-opacity": "fillOpacity",
  "stroke-width": "strokeWidth",
  "stroke-linecap": "strokeLinecap",
  "stroke-linejoin": "strokeLinejoin",
  "stroke-opacity": "strokeOpacity",
  "stroke-dasharray": "strokeDasharray",
  "stop-color": "stopColor",
  "stop-opacity": "stopOpacity",
  "clip-path": "clipPath",
};

function jsxAttrName(name) {
  if (name.startsWith("data-") || name.startsWith("aria-")) return name;
  if (ATTR_MAP[name]) return ATTR_MAP[name];
  if (name.includes("-")) {
    return name.replace(/-([a-z])/g, (_, c) => c.toUpperCase());
  }
  return name;
}

// arrow-up-fill-18 -> IconArrowUpFill18
function componentName(fileBase) {
  const pascal = fileBase
    .split("-")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");
  return `Icon${pascal}`;
}

function parsePaths(svg) {
  const paths = [];
  for (const tag of svg.matchAll(/<path\b([^>]*?)\/?>/g)) {
    const attrs = [];
    for (const attr of tag[1].matchAll(/([\w:-]+)="([^"]*)"/g)) {
      attrs.push(`${jsxAttrName(attr[1])}="${attr[2]}"`);
    }
    paths.push(`      <path ${attrs.join(" ")} />`);
  }
  return paths;
}

async function main() {
  const files = (await readdir(SVG_DIR))
    .filter((file) => file.endsWith(".svg"))
    .sort();

  if (files.length === 0) {
    throw new Error(`No .svg files found in ${SVG_DIR}`);
  }

  const components = [];
  for (const file of files) {
    const svg = await readFile(resolve(SVG_DIR, file), "utf8");
    const viewBox = svg.match(/viewBox="([^"]+)"/)?.[1] ?? "0 0 24 24";
    const nativeSize = Number(viewBox.split(/\s+/)[2]) || 24;
    const paths = parsePaths(svg);
    if (paths.length === 0) {
      throw new Error(`No <path> elements found in ${file}`);
    }

    const name = componentName(file.replace(/\.svg$/, ""));
    components.push(
      `export const ${name} = ({ size = ${nativeSize}, width, height, title, ...props }: IconProps) => (\n` +
        `  <svg\n` +
        `    xmlns="http://www.w3.org/2000/svg"\n` +
        `    viewBox="${viewBox}"\n` +
        `    width={width ?? size}\n` +
        `    height={height ?? size}\n` +
        `    {...props}\n` +
        `  >\n` +
        `    {title ? <title>{title}</title> : null}\n` +
        `${paths.join("\n")}\n` +
        `  </svg>\n` +
        `);`,
    );
  }

  const header = `// AUTO-GENERATED by scripts/build-icons.mjs from ./svg/*.svg.
// Do not edit by hand — edit the SVG source and run \`npm run build:icons\`.
import type { SVGProps } from "react";

export interface IconProps extends SVGProps<SVGSVGElement> {
  /** Square size in pixels; overridden by explicit width/height. */
  size?: number | string;
  /** Accessible title rendered as an SVG <title> element. */
  title?: string;
}
`;

  await writeFile(OUT_FILE, `${header}\n${components.join("\n\n")}\n`, "utf8");
  console.log(`Generated ${OUT_FILE} with ${components.length} icons.`);
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
